In [152]:
# Importing the libraries
import numpy as np

import pandas as pd


In [153]:
# Importing the dataset
col_names = ['timeStamp','Gender','Grade','Age','Length','Weight','ShoesSize']
dataset = pd.read_csv('human_features.csv')
dataset.set_axis(col_names, axis=1, inplace=True)
dataset


timeStamp Gender              Grade  Age  Length  \
0    2022/03/30 1:47:30 ص غرينتش+2    ذكر          الأعدادية   23     178   
1    2022/03/30 1:55:51 ص غرينتش+2   أنثى            الثالثة   21     155   
2    2022/03/30 1:55:58 ص غرينتش+2    ذكر            الثالثة   21     165   
3    2022/03/30 1:56:00 ص غرينتش+2    ذكر            الثالثة   22     173   
4    2022/03/30 1:59:30 ص غرينتش+2    ذكر  مش في الكلية اصلا   23     170   
..                             ...    ...                ...  ...     ...   
110  2022/03/31 3:58:49 م غرينتش+2    ذكر  مش في الكلية اصلا   22     165   
111  2022/03/31 4:50:20 م غرينتش+2   أنثى             ألاولي   19     159   
112  2022/03/31 4:52:13 م غرينتش+2   أنثى             ألاولي   19     159   
113  2022/03/31 5:29:30 م غرينتش+2    ذكر            الرابعة   22     176   
114  2022/03/31 6:18:20 م غرينتش+2   أنثى  مش في الكلية اصلا   25     176   

     Weight  ShoesSize  
0        74         43  
1        64         39  
2        65         41  
3        80         44  
4        82         44  
..      ...        ...  
110      75         40  
111      50         37  
112      50         37  
113      75         43  
114      89         40  

[115 rows x 7 columns]

In [154]:
# Encode Gender
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
dataset['Gender'] = label_encoder.fit_transform(dataset['Gender'])
dataset

timeStamp  Gender              Grade  Age  Length  \
0    2022/03/30 1:47:30 ص غرينتش+2       1          الأعدادية   23     178   
1    2022/03/30 1:55:51 ص غرينتش+2       0            الثالثة   21     155   
2    2022/03/30 1:55:58 ص غرينتش+2       1            الثالثة   21     165   
3    2022/03/30 1:56:00 ص غرينتش+2       1            الثالثة   22     173   
4    2022/03/30 1:59:30 ص غرينتش+2       1  مش في الكلية اصلا   23     170   
..                             ...     ...                ...  ...     ...   
110  2022/03/31 3:58:49 م غرينتش+2       1  مش في الكلية اصلا   22     165   
111  2022/03/31 4:50:20 م غرينتش+2       0             ألاولي   19     159   
112  2022/03/31 4:52:13 م غرينتش+2       0             ألاولي   19     159   
113  2022/03/31 5:29:30 م غرينتش+2       1            الرابعة   22     176   
114  2022/03/31 6:18:20 م غرينتش+2       0  مش في الكلية اصلا   25     176   

     Weight  ShoesSize  
0        74         43  
1        64         39  
2        65         41  
3        80         44  
4        82         44  
..      ...        ...  
110      75         40  
111      50         37  
112      50         37  
113      75         43  
114      89         40  

[115 rows x 7 columns]

In [156]:
# independent variables (Gender,length) >>>>> features
X = dataset.iloc[:, [1,5]].values
# dependent variable (weight) >>>> output 
y = dataset.iloc[:, 5].values

y

array([ 74,  64,  65,  80,  82,  92,  65, 112, 113,  70,  68,  90,  61,
        76,  83,  75,  74,  78,  65,  75,  68,  70,  59,  61,  72,  86,
        75,  77,  70,  74,  72,  65,  75,  71,  75,  85,  50,  70,  80,
        60,  70,  47,  84,  64,  73,  72,  77,  73,  80,  95,  88,  50,
        80, 100,  64,  62,  80,  70,  87,  65,  80,  75,  67,  58,  60,
        70,  91,  73,  62,  57,  80,  70,  85,  52,  70,  83, 100,  62,
        60,  77,  76,  75,  68,  85,  85,  99,  69,  57,  85, 102,  74,
        95,  83,  70,  69,  65, 117, 117,  68,  70,  75,  85,  75,  62,
        74,  85,  72,  68,  60,  96,  75,  50,  50,  75,  89], dtype=int64)

In [159]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
y_test

array([ 68,  70,  91,  50, 112,  60,  95, 102,  72,  67,  72,  65,  70,
        59,  64,  68,  72,  52,  80,  80,  74,  76,  75], dtype=int64)

In [160]:
from sklearn.svm import SVR
regressor = SVR()  # object or instance from SVR
regressor.fit(X_train, np.ravel(y_train,order='C')) # train the model


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [162]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([71.08210268, 72.10975127, 82.88031014, 64.00382794, 88.42724779,
       67.35705788, 84.51127059, 86.75039327, 73.16191802, 70.5798158 ,
       73.16191802, 69.60280361, 72.10975127, 66.9510114 , 69.1297916 ,
       71.08210268, 73.16191802, 64.53657219, 77.45852579, 77.45852579,
       74.22700372, 75.30863078, 74.76914162])

In [163]:
# comparing actual data with predicted data
df= pd.DataFrame({'Actual': list(y_test), 'Predicted': y_pred})
df

Actual  Predicted
0       68  71.082103
1       70  72.109751
2       91  82.880310
3       50  64.003828
4      112  88.427248
5       60  67.357058
6       95  84.511271
7      102  86.750393
8       72  73.161918
9       67  70.579816
10      72  73.161918
11      65  69.602804
12      70  72.109751
13      59  66.951011
14      64  69.129792
15      68  71.082103
16      72  73.161918
17      52  64.536572
18      80  77.458526
19      80  77.458526
20      74  74.227004
21      76  75.308631
22      75  74.769142

In [164]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
from math import sqrt
print('Mean Absolute Error    :', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error     :', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', sqrt(mean_squared_error(y_test, y_pred)))

Mean Absolute Error    : 5.769273928271465
Mean Squared Error     : 66.98057833977043
Root Mean Squared Error: 8.184166319165955
